### ISSUE TITLE
Test RS485 communication with values > 127

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/PQ9EGSE_Software#2]
Test the RS485 communication between PC and EGSE for addresses > 127 and byte values > 127

**Comment by MFvandenBos** [comment]
I am not seeing any problems with values above 127. 


Shall we close this or leave it open until the next update of the HPI communication?

**Comment by MFvandenBos** [comment]
Issue has been tested, HPI is now working for values > 127
